#!/usr/bin/env node
/* eslint-disable @typescript-eslint/no-require-imports */
const fs=require("node:fs"),path=require("node:path"),crypto=require("node:crypto");
const args=process.argv.slice(2),cmd=args[0],get=(n,d)=>{const i=args.indexOf(`--${n}`);return i<0?d:args[i+1]};
const canonical=v=>v===null||typeof v!=="object"?JSON.stringify(v):Array.isArray(v)?`[${v.map(canonical).join(",")}]`:`{${Object.keys(v).sort().map(k=>`${JSON.stringify(k)}:${canonical(v[k])}`).join(",")}}`;
function noOverwrite(p){if(fs.existsSync(p))throw new Error(`Tệp đã tồn tại, không ghi đè: ${p}`)}
if(cmd==="init-keys"){const dir=path.resolve(get("out","."));fs.mkdirSync(dir,{recursive:true});const priv=path.join(dir,"chu-nhiem-so-private.pem"),pub=path.join(dir,"chu-nhiem-so-public.pem");noOverwrite(priv);noOverwrite(pub);const pair=crypto.generateKeyPairSync("ed25519");fs.writeFileSync(priv,pair.privateKey.export({type:"pkcs8",format:"pem"}),{mode:0o600});fs.writeFileSync(pub,pair.publicKey.export({type:"spki",format:"pem"}));console.log(`Đã tạo khóa. PRIVATE KEY chỉ lưu tại: ${priv}\nPublic key: ${pub}\nHãy sao lưu private key ngoại tuyến; không đưa vào Git hoặc bản khách hàng.`)}
else if(cmd==="issue-license"){const key=path.resolve(get("private-key"));const out=path.resolve(get("out"));noOverwrite(out);const starts=get("starts"),expires=get("expires");if(!/^\d{4}-\d{2}-\d{2}$/.test(starts)||!/^\d{4}-\d{2}-\d{2}$/.test(expires)||expires<starts)throw new Error("Ngày bắt đầu/kết thúc không hợp lệ.");const payload={schemaVersion:1,licenseId:crypto.randomUUID(),customerId:get("customer"),customerName:get("name"),schoolName:get("school"),issuedAt:new Date().toISOString(),startsAt:`${starts}T00:00:00+07:00`,expiresAt:expires,licenseType:get("type","LOCAL_PORTABLE"),installationId:get("installation",null),maxSchools:+get("max-schools",1),maxClasses:+get("max-classes",5),maxStudents:+get("max-students",250),maxChildAccounts:+get("max-accounts",30),enabledFeatures:get("features","ATTENDANCE,COMPETITION,REPORTS,CLASS_ACCOUNTS,SUBJECT_TEACHERS").split(","),gracePeriodDays:+get("grace",7),issuerName:get("issuer","CHỦ SỞ HỮU PHẦN MỀM"),productCode:"CHU_NHIEM_SO",nonce:crypto.randomBytes(24).toString("base64url")};const signature=crypto.sign(null,Buffer.from(canonical(payload)),fs.readFileSync(key)).toString("base64");fs.writeFileSync(out,JSON.stringify({payload,signature},null,2));console.log(`Đã tạo license: ${out}\nLicense ID: ${payload.licenseId}`)}
else if(cmd==="renew-license"){const oldFile=path.resolve(get("file")),keyFile=path.resolve(get("private-key")),pubFile=path.resolve(get("public-key")),out=path.resolve(get("out"));noOverwrite(out);const old=JSON.parse(fs.readFileSync(oldFile,"utf8"));const valid=crypto.verify(null,Buffer.from(canonical(old.payload)),fs.readFileSync(pubFile),Buffer.from(old.signature,"base64"));if(!valid)throw new Error("License cũ có chữ ký không hợp lệ.");const expires=get("expires");if(!/^\d{4}-\d{2}-\d{2}$/.test(expires)||expires<=old.payload.expiresAt)throw new Error("Ngày hết hạn mới phải sau thời hạn hiện tại.");const payload={...old.payload,licenseId:crypto.randomUUID(),previousLicenseId:old.payload.licenseId,issuedAt:new Date().toISOString(),expiresAt:expires,nonce:crypto.randomBytes(24).toString("base64url")};const signature=crypto.sign(null,Buffer.from(canonical(payload)),fs.readFileSync(keyFile)).toString("base64");fs.writeFileSync(out,JSON.stringify({payload,signature},null,2));console.log(`Đã tạo license gia hạn: ${out}\nLicense cũ: ${old.payload.licenseId}\nLicense mới: ${payload.licenseId}`)}else if(cmd==="verify-license"||cmd==="inspect-license"){const lic=JSON.parse(fs.readFileSync(path.resolve(get("file")),"utf8"));if(cmd==="inspect-license")console.log(JSON.stringify(lic.payload,null,2));else{const ok=crypto.verify(null,Buffer.from(canonical(lic.payload)),fs.readFileSync(path.resolve(get("public-key"))),Buffer.from(lic.signature,"base64"));console.log(ok?"Chữ ký license hợp lệ.":"Chữ ký license KHÔNG hợp lệ.");process.exitCode=ok?0:2}}
else{console.log("Lệnh: init-keys | issue-license | renew-license | inspect-license | verify-license\nDùng --out, --private-key, --public-key, --file và các trường khách hàng tương ứng.")}