Add-Type -AssemblyName System.Windows.Forms
Add-Type -AssemblyName System.Drawing
[System.Windows.Forms.Application]::EnableVisualStyles()
$root = Resolve-Path (Join-Path $PSScriptRoot "..\..")
$cli = Join-Path $PSScriptRoot "cli.cjs"
$form = New-Object System.Windows.Forms.Form
$form.Text = "CHỦ NHIỆM SỐ - Công cụ tạo license"
$form.Size = New-Object System.Drawing.Size(760,760)
$form.StartPosition = "CenterScreen"
$form.Font = New-Object System.Drawing.Font("Segoe UI",10)
$form.AutoScroll = $true
$y = 20
function Add-Label($text,$top){$label=New-Object System.Windows.Forms.Label;$label.Text=$text;$label.Location=New-Object System.Drawing.Point(24,$top);$label.Size=New-Object System.Drawing.Size(210,28);$form.Controls.Add($label)}
function Add-Text($name,$top,$default=""){$box=New-Object System.Windows.Forms.TextBox;$box.Name=$name;$box.Text=$default;$box.Location=New-Object System.Drawing.Point(240,$top);$box.Size=New-Object System.Drawing.Size(450,28);$form.Controls.Add($box);return $box}
$warning=New-Object System.Windows.Forms.Label;$warning.Text="PRIVATE KEY chỉ lưu trên máy người bán. Hãy sao lưu ngoại tuyến và tuyệt đối không gửi cho khách.";$warning.ForeColor=[System.Drawing.Color]::DarkRed;$warning.Font=New-Object System.Drawing.Font("Segoe UI",10,[System.Drawing.FontStyle]::Bold);$warning.Location=New-Object System.Drawing.Point(24,$y);$warning.Size=New-Object System.Drawing.Size(680,44);$form.Controls.Add($warning);$y+=55
Add-Label "Private key" $y;$private=Add-Text "privateKey" $y; $browse=New-Object System.Windows.Forms.Button;$browse.Text="Chọn…";$browse.Location=New-Object System.Drawing.Point(600,$y);$browse.Size=New-Object System.Drawing.Size(90,28);$form.Controls.Add($browse);$private.Size=New-Object System.Drawing.Size(350,28);$y+=38
$init=New-Object System.Windows.Forms.Button;$init.Text="Khởi tạo cặp khóa lần đầu";$init.Location=New-Object System.Drawing.Point(240,$y);$init.Size=New-Object System.Drawing.Size(230,32);$form.Controls.Add($init);$y+=45
Add-Label "Tên khách hàng *" $y;$customerName=Add-Text "customerName" $y;$y+=38
Add-Label "Tên trường *" $y;$school=Add-Text "school" $y;$y+=38
Add-Label "Mã cài đặt *" $y;$installation=Add-Text "installation" $y;$y+=38
Add-Label "Ngày bắt đầu *" $y;$starts=New-Object System.Windows.Forms.DateTimePicker;$starts.Format="Custom";$starts.CustomFormat="dd/MM/yyyy";$starts.Location=New-Object System.Drawing.Point(240,$y);$starts.Size=New-Object System.Drawing.Size(180,28);$form.Controls.Add($starts);$y+=38
Add-Label "Ngày hết hạn *" $y;$expires=New-Object System.Windows.Forms.DateTimePicker;$expires.Format="Custom";$expires.CustomFormat="dd/MM/yyyy";$expires.Value=(Get-Date).AddYears(1);$expires.Location=New-Object System.Drawing.Point(240,$y);$expires.Size=New-Object System.Drawing.Size(180,28);$form.Controls.Add($expires);$y+=38
function Add-Number($labelText,$top,$value){Add-Label $labelText $top;$number=New-Object System.Windows.Forms.NumericUpDown;$number.Minimum=1;$number.Maximum=100000;$number.Value=$value;$number.Location=New-Object System.Drawing.Point(240,$top);$number.Size=New-Object System.Drawing.Size(180,28);$form.Controls.Add($number);return $number}
$maxClasses=Add-Number "Số lớp" $y 5;$y+=38;$maxStudents=Add-Number "Số học sinh" $y 250;$y+=38;$maxAccounts=Add-Number "Số tài khoản con" $y 30;$y+=42
Add-Label "Tính năng được mở" $y;$features=New-Object System.Windows.Forms.CheckedListBox;$features.Location=New-Object System.Drawing.Point(240,$y);$features.Size=New-Object System.Drawing.Size(450,115);@("ATTENDANCE - Điểm danh","COMPETITION - Thi đua","REPORTS - Báo cáo","CLASS_ACCOUNTS - Tài khoản lớp","SUBJECT_TEACHERS - Giáo viên bộ môn")|ForEach-Object{[void]$features.Items.Add($_,$true)};$form.Controls.Add($features);$y+=130
$preview=New-Object System.Windows.Forms.Button;$preview.Text="Xem trước";$preview.Location=New-Object System.Drawing.Point(240,$y);$preview.Size=New-Object System.Drawing.Size(140,38);$form.Controls.Add($preview)
$create=New-Object System.Windows.Forms.Button;$create.Text="Tạo file license";$create.Location=New-Object System.Drawing.Point(395,$y);$create.Size=New-Object System.Drawing.Size(180,38);$create.BackColor=[System.Drawing.Color]::LightSeaGreen;$form.Controls.Add($create)
function Validate-Form { if(-not (Test-Path $private.Text)){[System.Windows.Forms.MessageBox]::Show("Vui lòng chọn private key hợp lệ.","Thiếu thông tin","OK","Warning");return $false};if([string]::IsNullOrWhiteSpace($customerName.Text)-or[string]::IsNullOrWhiteSpace($school.Text)-or[string]::IsNullOrWhiteSpace($installation.Text)){[System.Windows.Forms.MessageBox]::Show("Vui lòng nhập tên khách hàng, trường và mã cài đặt.","Thiếu thông tin","OK","Warning");return $false};if($expires.Value.Date -lt $starts.Value.Date){[System.Windows.Forms.MessageBox]::Show("Ngày hết hạn phải từ ngày bắt đầu trở đi.","Ngày không hợp lệ","OK","Warning");return $false};return $true}
function Feature-Codes { $codes=@();foreach($item in $features.CheckedItems){$codes += ($item.ToString().Split(" ")[0])};return ($codes -join ",")}
function Preview-Text { return "Khách hàng: $($customerName.Text)`nTrường: $($school.Text)`nMã cài đặt: $($installation.Text)`nThời hạn: $($starts.Value.ToString('dd/MM/yyyy')) - $($expires.Value.ToString('dd/MM/yyyy'))`nGiới hạn: $($maxClasses.Value) lớp, $($maxStudents.Value) học sinh, $($maxAccounts.Value) tài khoản con`nTính năng: $(Feature-Codes)" }
$browse.Add_Click({$dialog=New-Object System.Windows.Forms.OpenFileDialog;$dialog.Filter="Private key (*.pem)|*.pem";if($dialog.ShowDialog()-eq"OK"){$private.Text=$dialog.FileName}})
$init.Add_Click({$dialog=New-Object System.Windows.Forms.FolderBrowserDialog;$dialog.Description="Chọn thư mục ngoài dự án để lưu cặp khóa";if($dialog.ShowDialog()-eq"OK"){$output=& node $cli init-keys --out $dialog.SelectedPath 2>&1;if($LASTEXITCODE-eq 0){$private.Text=Join-Path $dialog.SelectedPath "chu-nhiem-so-private.pem";[System.Windows.Forms.MessageBox]::Show("Đã tạo khóa. Hãy sao lưu cả thư mục này ở nơi ngoại tuyến được bảo vệ.`n`n$output","Thành công")}else{[System.Windows.Forms.MessageBox]::Show("Không thể tạo khóa:`n$output","Lỗi")}}})
$preview.Add_Click({if(Validate-Form){[System.Windows.Forms.MessageBox]::Show((Preview-Text),"Xem trước license")}})
$create.Add_Click({if(-not(Validate-Form)){return};$answer=[System.Windows.Forms.MessageBox]::Show((Preview-Text)+"`n`nTạo file license với thông tin trên?","Xác nhận","YesNo","Question");if($answer-ne"Yes"){return};$save=New-Object System.Windows.Forms.SaveFileDialog;$save.Filter="License CHỦ NHIỆM SỐ (*.license)|*.license";$save.FileName="CHU_NHIEM_SO_$((Get-Date).ToString('yyyyMMddHHmmss'))_$($expires.Value.ToString('yyyy-MM-dd')).license";if($save.ShowDialog()-ne"OK"){return};$customer="KH-$((Get-Date).ToString('yyyyMMddHHmmss'))";$arguments=@($cli,"issue-license","--private-key",$private.Text,"--out",$save.FileName,"--customer",$customer,"--name",$customerName.Text,"--school",$school.Text,"--installation",$installation.Text,"--type","LOCAL_DEVICE_BOUND","--starts",$starts.Value.ToString("yyyy-MM-dd"),"--expires",$expires.Value.ToString("yyyy-MM-dd"),"--max-classes",$maxClasses.Value,"--max-students",$maxStudents.Value,"--max-accounts",$maxAccounts.Value,"--features",(Feature-Codes));$output=& node @arguments 2>&1;if($LASTEXITCODE-eq 0){[System.Windows.Forms.MessageBox]::Show("Đã tạo file license:`n$($save.FileName)`n`nChỉ gửi file .license này cho khách. Không gửi private key.","Tạo license thành công")}else{[System.Windows.Forms.MessageBox]::Show("Không thể tạo license:`n$output","Lỗi")}})
[void]$form.ShowDialog()