import { createPublicKey, verify } from "node:crypto";
export const PRODUCT_CODE = "CHU_NHIEM_SO";
export type LicensePayload = { schemaVersion: 1; licenseId: string; customerId: string; customerName: string; schoolName: string; issuedAt: string; startsAt: string; expiresAt: string; licenseType: "LOCAL_PORTABLE" | "LOCAL_DEVICE_BOUND"; installationId: string | null; maxSchools: number; maxClasses: number; maxStudents: number; maxChildAccounts: number; enabledFeatures: string[]; gracePeriodDays: number; issuerName: string; productCode: string; previousLicenseId?: string; nonce: string };
export type SignedLicense = { payload: LicensePayload; signature: string };
export type EvaluatedLicenseStatus = "INVALID_PRODUCT" | "WRONG_INSTALLATION" | "SCHEDULED" | "ACTIVE" | "GRACE" | "READ_ONLY_EXPIRED";
export function canonicalizePayload(value: unknown): string { if (value === null || typeof value !== "object") return JSON.stringify(value); if (Array.isArray(value)) return `[${value.map(canonicalizePayload).join(",")}]`; const object = value as Record<string, unknown>; return `{${Object.keys(object).sort().map(key => `${JSON.stringify(key)}:${canonicalizePayload(object[key])}`).join(",")}}`; }
export function parseLicense(text: string): SignedLicense { const value = JSON.parse(text) as SignedLicense; const p = value?.payload; if (!p || typeof value.signature !== "string" || p.schemaVersion !== 1 || typeof p.licenseId !== "string" || typeof p.customerId !== "string" || typeof p.startsAt !== "string" || typeof p.expiresAt !== "string" || !Array.isArray(p.enabledFeatures)) throw new Error("Tệp license không đúng cấu trúc."); return value; }
export function verifyLicenseSignature(license: SignedLicense, publicKeyPem: string) { try { return verify(null, Buffer.from(canonicalizePayload(license.payload)), createPublicKey(publicKeyPem), Buffer.from(license.signature, "base64")); } catch { return false; } }
const endOfDay = (iso: string) => new Date(`${iso.slice(0, 10)}T23:59:59.999+07:00`);
export function evaluateLicenseStatus(p: LicensePayload, now = new Date(), installationId?: string): EvaluatedLicenseStatus { if (p.productCode !== PRODUCT_CODE) return "INVALID_PRODUCT"; if (p.licenseType === "LOCAL_DEVICE_BOUND" && p.installationId !== installationId) return "WRONG_INSTALLATION"; const start = new Date(p.startsAt), end = endOfDay(p.expiresAt), grace = new Date(end.getTime() + Math.max(0, p.gracePeriodDays) * 86400000); if (now < start) return "SCHEDULED"; if (now <= end) return "ACTIVE"; if (now <= grace) return "GRACE"; return "READ_ONLY_EXPIRED"; }
export function getRemainingDays(p: LicensePayload, now = new Date()) { return Math.max(0, Math.ceil((endOfDay(p.expiresAt).getTime() - now.getTime()) / 86400000)); }
export function assertFeatureEnabled(p: LicensePayload, feature: string) { if (!p.enabledFeatures.includes(feature)) throw new Error("Tính năng này chưa được cấp trong license."); }
export function assertWithinLimit(current: number, max: number, label: string) { if (current >= max) throw new Error(`${label} đã đạt giới hạn license.`); }