import { afterEach, describe, expect, it, vi } from "vitest";
import { mkdtemp, readFile, rm } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { generateKeyPairSync, sign } from "node:crypto";
import { FileLicenseStorage } from "./storage";
import { canonicalizePayload, type LicensePayload } from "./core";
import { getLicenseRuntime } from "./runtime";
import { getInstallationId } from "./installation";
const dirs: string[] = [];
afterEach(async () => { delete process.env.CHU_NHIEM_SO_DATA_DIR; delete process.env.LICENSE_PUBLIC_KEY_PEM; delete process.env.LICENSE_ENFORCEMENT; vi.unstubAllEnvs(); await Promise.all(dirs.splice(0).map(dir => rm(dir, { recursive: true, force: true }))); });
const payload: LicensePayload = { schemaVersion: 1, licenseId: "L1", customerId: "C1", customerName: "Khách hàng thử nghiệm", schoolName: "Trường thử nghiệm", issuedAt: "2026-08-01T00:00:00Z", startsAt: "2026-08-01T00:00:00+07:00", expiresAt: "2026-08-31", licenseType: "LOCAL_PORTABLE", installationId: null, maxSchools: 1, maxClasses: 5, maxStudents: 250, maxChildAccounts: 30, enabledFeatures: ["ATTENDANCE"], gracePeriodDays: 0, issuerName: "Người phát hành", productCode: "CHU_NHIEM_SO", nonce: "n" };
async function setup() { const dir = await mkdtemp(join(tmpdir(), "cns-license-")); dirs.push(dir); const pair = generateKeyPairSync("ed25519"), signed = { payload, signature: sign(null, Buffer.from(canonicalizePayload(payload)), pair.privateKey).toString("base64") }; return { dir, pair, signed }; }
describe("LicenseStorage và runtime", () => { it("thay thế atomic và giữ file trước", async () => { const { dir, signed } = await setup(), file = join(dir, "license", "current.license"), store = new FileLicenseStorage(file); await store.replaceAtomic(JSON.stringify(signed)); await store.replaceAtomic(JSON.stringify({ ...signed, payload: { ...payload, licenseId: "L2" } })); expect(JSON.parse(await readFile(`${file}.previous`, "utf8")).payload.licenseId).toBe("L1"); }); it("mã cài đặt ổn định qua nhiều lần đọc", async () => { const { dir } = await setup(); process.env.CHU_NHIEM_SO_DATA_DIR = dir; expect(await getInstallationId()).toBe(await getInstallationId()); }); it("production luôn bắt buộc license dù biến enforcement bằng 0", async () => { const { dir } = await setup(); process.env.CHU_NHIEM_SO_DATA_DIR = dir; process.env.LICENSE_ENFORCEMENT = "0"; vi.stubEnv("NODE_ENV", "production"); const state = await getLicenseRuntime(); expect(state.status).toBe("MISSING"); expect(state.writeAllowed).toBe(false); }); it("chặn ghi khi bật enforcement mà chưa có license", async () => { const { dir } = await setup(); process.env.CHU_NHIEM_SO_DATA_DIR = dir; process.env.LICENSE_ENFORCEMENT = "1"; expect((await getLicenseRuntime()).writeAllowed).toBe(false); }); it("license hoạt động cho ghi và license hết hạn chỉ đọc", async () => { const { dir, pair, signed } = await setup(); process.env.CHU_NHIEM_SO_DATA_DIR = dir; process.env.LICENSE_ENFORCEMENT = "1"; process.env.LICENSE_PUBLIC_KEY_PEM = pair.publicKey.export({ type: "spki", format: "pem" }).toString(); await new FileLicenseStorage().replaceAtomic(JSON.stringify(signed)); expect((await getLicenseRuntime(new Date("2026-08-15"))).writeAllowed).toBe(true); const expired = await getLicenseRuntime(new Date("2026-09-02")); expect(expired.status).toBe("READ_ONLY_EXPIRED"); expect(expired.writeAllowed).toBe(false); }); });