"use server";
import bcrypt from "bcryptjs";
import { revalidatePath } from "next/cache";
import { z } from "zod";
import { assertWriteAllowed } from "@/lib/license/runtime";
import { requireSystemAdmin } from "@/lib/auth";
import { db } from "@/lib/db";
const strong = z.string().min(10).regex(/[A-Z]/).regex(/[a-z]/).regex(/[0-9]/).regex(/[^A-Za-z0-9]/);
const allowedRoles = z.enum(["TEACHER", "CLASS_MONITOR", "ACADEMIC_VICE_MONITOR", "DISCIPLINE_VICE_MONITOR", "TEAM_LEADER", "STUDENT", "GUARDIAN"]);
export async function createManagedAccount(_: unknown, formData: FormData) { await assertWriteAllowed(); const admin = await requireSystemAdmin(), parsed = z.object({ name: z.string().min(2), identifier: z.string().min(3), password: strong, role: allowedRoles, schoolId: z.string().min(1), classId: z.string().optional(), teamId: z.string().optional(), startDate: z.string().optional(), endDate: z.string().optional() }).safeParse(Object.fromEntries(formData)); if (!parsed.success) return { error: "Thông tin hoặc mật khẩu tạm chưa hợp lệ." }; const data = parsed.data, identifier = data.identifier.trim().toLowerCase(); if (data.role === "TEAM_LEADER" && !data.teamId) return { error: "Tổ trưởng bắt buộc phải chọn tổ." }; if (await db.user.findFirst({ where: { OR: [{ email: identifier }, { username: identifier }] } })) return { error: "Tên đăng nhập hoặc email đã tồn tại." }; if (data.classId) { const classroom = await db.classroom.findFirst({ where: { id: data.classId, schoolId: data.schoolId } }); if (!classroom) return { error: "Lớp không thuộc trường đã chọn." }; } if (data.teamId && !await db.team.findFirst({ where: { id: data.teamId, classId: data.classId } })) return { error: "Tổ không thuộc lớp đã chọn." }; const user = await db.$transaction(async tx => { const created = await tx.user.create({ data: { name: data.name, email: identifier.includes("@") ? identifier : `${identifier}@local.chunhiemso`, username: identifier.includes("@") ? null : identifier, passwordHash: await bcrypt.hash(data.password, 12), role: data.role, schoolId: data.schoolId, classId: data.classId || null, teamId: data.teamId || null, mustChangePassword: true } }); if (data.classId) await tx.classMembership.create({ data: { userId: created.id, classId: data.classId, role: data.role, startDate: data.startDate ? new Date(`${data.startDate}T00:00:00Z`) : new Date(), endDate: data.endDate ? new Date(`${data.endDate}T23:59:59Z`) : null } }); await tx.auditLog.create({ data: { userId: admin.id, action: "CREATE_MANAGED_ACCOUNT", entityType: "User", entityId: created.id, schoolId: data.schoolId, classId: data.classId || null, after: { role: data.role, mustChangePassword: true } } }); return created; }); revalidatePath("/tai-khoan"); return { ok: true, message: `Đã tạo tài khoản ${user.name}.` }; }
export async function setAccountActive(formData: FormData) { await assertWriteAllowed(); const admin = await requireSystemAdmin(), id = z.string().parse(formData.get("id")), active = formData.get("active") === "true"; if (id === admin.id && !active) throw new Error("Không thể tự khóa tài khoản quản trị đang đăng nhập."); const target = await db.user.findUnique({ where: { id } }); if (!target) throw new Error("Không tìm thấy tài khoản."); await db.$transaction([db.user.update({ where: { id }, data: { active } }), db.auditLog.create({ data: { userId: admin.id, action: active ? "UNLOCK_ACCOUNT" : "LOCK_ACCOUNT", entityType: "User", entityId: id, schoolId: target.schoolId, classId: target.classId, before: { active: target.active }, after: { active } } })]); revalidatePath("/tai-khoan"); }
export async function resetAccountPassword(_: unknown, formData: FormData) { await assertWriteAllowed(); const admin = await requireSystemAdmin(), parsed = z.object({ id: z.string(), password: strong }).safeParse(Object.fromEntries(formData)); if (!parsed.success) return { error: "Mật khẩu tạm chưa đủ mạnh." }; const target = await db.user.findUnique({ where: { id: parsed.data.id } }); if (!target) return { error: "Không tìm thấy tài khoản." }; await db.$transaction([db.user.update({ where: { id: target.id }, data: { passwordHash: await bcrypt.hash(parsed.data.password, 12), mustChangePassword: true } }), db.auditLog.create({ data: { userId: admin.id, action: "RESET_ACCOUNT_PASSWORD", entityType: "User", entityId: target.id, schoolId: target.schoolId, classId: target.classId, after: { mustChangePassword: true } } })]); revalidatePath("/tai-khoan"); return { ok: true, message: "Đã đặt mật khẩu tạm và yêu cầu đổi ở lần đăng nhập tiếp theo." }; }