"use server";
import bcrypt from "bcryptjs";
import { assertWriteAllowed } from "@/lib/license/runtime";
import { cookies, headers } from "next/headers";
import { revalidatePath } from "next/cache";
import { redirect } from "next/navigation";
import { z } from "zod";
import { createSession, requireTeacher, requireUser } from "@/lib/auth";
import { db } from "@/lib/db";
import { calculateScore, rankScores } from "@/lib/scoring";
import { consumeLoginLimits, normalizeLoginIdentifier, resetLoginEmailLimit } from "@/lib/rate-limit";
import { canPerform } from "@/lib/authorization";
export async function login(_: unknown, formData: FormData) {
  const parsed = z.object({ identifier: z.string().min(3), password: z.string().min(8) }).safeParse(Object.fromEntries(formData));
  if (!parsed.success) return { error: "Vui lòng kiểm tra tên đăng nhập/email và mật khẩu." };
  const identifier = normalizeLoginIdentifier(parsed.data.identifier), requestHeaders = await headers(), ip = requestHeaders.get("x-real-ip") || requestHeaders.get("x-forwarded-for")?.split(",")[0]?.trim() || "unknown";
  const limit = consumeLoginLimits(identifier, ip, process.env.NODE_ENV === "production" ? 5 : 50, process.env.NODE_ENV === "production" ? 25 : 200);
  if (!limit.allowed) return { error: "Bạn đã thử đăng nhập quá nhiều lần. Vui lòng chờ rồi thử lại." };
  const user = await db.user.findFirst({ where: { OR: [{ email: identifier }, { username: identifier }] } });
  if (!user || !user.active || !await bcrypt.compare(parsed.data.password, user.passwordHash)) return { error: "Tên đăng nhập/email hoặc mật khẩu chưa đúng." };
  resetLoginEmailLimit(identifier); await db.user.update({ where: { id: user.id }, data: { lastLoginAt: new Date() } }); await createSession(user.id); redirect(user.mustChangePassword ? "/tai-khoan-cua-toi?bat-buoc=1" : "/");
}export async function logout(){(await cookies()).delete("cns_session");redirect("/dang-nhap");}
export async function setLocale(locale:"vi"|"en"){const user=await requireUser();await db.user.update({where:{id:user.id},data:{locale}});(await cookies()).set("locale",locale,{path:"/",sameSite:"lax"});revalidatePath("/");}
export async function approveEvent(formData:FormData){await assertWriteAllowed();const user=await requireTeacher();const id=z.string().parse(formData.get("id"));const event=await db.competitionEvent.findUnique({where:{id},include:{week:true}});if(!event||event.week.classId!==user.classId||event.week.status==="FINALIZED")throw new Error("Không có quyền hoặc tuần đã chốt");await db.$transaction([db.competitionEvent.update({where:{id},data:{status:"APPROVED",approvedPoints:event.proposedPoints,approvedBy:user.id,approvedAt:new Date()}}),db.auditLog.create({data:{userId:user.id,action:"APPROVE_EVENT",entityType:"CompetitionEvent",entityId:id,classId:user.classId,after:{status:"APPROVED"}}})]);revalidatePath("/");}
export async function updateAttendance(formData:FormData){await assertWriteAllowed();const user=await requireUser();const id=z.string().parse(formData.get("id"));const status=z.enum(["PRESENT","ABSENT_EXCUSED","ABSENT_UNEXCUSED","LATE","LEFT_EARLY"]).parse(formData.get("status"));const rec=await db.attendanceRecord.findUnique({where:{id},include:{session:true,event:true,student:{select:{classId:true,teamId:true}}}});if(!rec||!await canPerform(user,"attendance.update",{classId:rec.student.classId,teamId:rec.student.teamId}))throw new Error("Bạn không có quyền điểm danh học sinh này.");if(rec.session.weekId&&(await db.competitionWeek.findUnique({where:{id:rec.session.weekId}}))?.status==="FINALIZED")throw new Error("Tuần đã chốt");await db.$transaction(async tx=>{await tx.attendanceRecord.update({where:{id},data:{status,approved:user.role==="TEACHER"}});if(rec.event)await tx.competitionEvent.update({where:{id:rec.event.id},data:{status:"CANCELLED",rejectionReason:"Thay đổi trạng thái điểm danh"}});if(user.role==="TEACHER"&&(status==="LATE"||status==="ABSENT_UNEXCUSED")){const code=status==="LATE"?"CC-DM":"CC-VKP";const rule=await tx.ruleItem.findFirst({where:{ruleSet:{weeks:{some:{id:rec.session.weekId}}},code}});if(rule)await tx.competitionEvent.create({data:{weekId:rec.session.weekId,studentId:rec.studentId,ruleItemId:rule.id,attendanceId:id,occurredAt:rec.session.date,proposedPoints:rule.points,approvedPoints:rule.points,description:status==="LATE"?"Tự động từ điểm danh: Đi muộn":"Tự động từ điểm danh: Vắng không phép",status:"APPROVED",creatorId:user.id,approvedBy:user.id,approvedAt:new Date()}});}});revalidatePath("/");}
export async function finalizeWeek(formData:FormData){await assertWriteAllowed();const user=await requireTeacher();const weekId=z.string().parse(formData.get("weekId"));const week=await db.competitionWeek.findUnique({where:{id:weekId},include:{ruleSet:true,events:{include:{ruleItem:true}},adjustments:true,classroom:{include:{students:true}},sessions:{include:{records:true}}}});if(!week||week.classId!==user.classId)throw new Error("Không có quyền");if(week.events.some(e=>e.status==="PENDING"))throw new Error("Vẫn còn sự kiện chờ duyệt");if(week.sessions.some(s=>s.records.some(r=>r.status==="NOT_MARKED")))throw new Error("Vẫn còn buổi chưa điểm danh");const ranked=rankScores(week.classroom.students.map(student=>{const detail=calculateScore(week.ruleSet.initialScore,week.events.filter(e=>e.studentId===student.id).map(e=>({status:e.status,points:e.approvedPoints??e.proposedPoints,type:e.ruleItem.type,occurredAt:e.occurredAt,criterionId:e.ruleItemId,dailyLimit:e.ruleItem.dailyLimit,weeklyLimit:e.ruleItem.weeklyLimit})),week.adjustments.filter(a=>a.studentId===student.id).map(a=>a.points));return{student,score:detail.finalScore,detail}}));await db.$transaction(async tx=>{await tx.studentWeeklyResult.deleteMany({where:{weekId}});for(const row of ranked)await tx.studentWeeklyResult.create({data:{weekId,studentId:row.student.id,bonus:row.detail.bonus,penalty:row.detail.penalty,adjustment:row.detail.adjustment,finalScore:row.detail.finalScore,rank:row.rank,grade:row.detail.grade,snapshot:JSON.parse(JSON.stringify(row.detail))}});await tx.competitionWeek.update({where:{id:weekId},data:{status:"FINALIZED",finalizedAt:new Date(),finalizedBy:user.id}});await tx.auditLog.create({data:{userId:user.id,action:"FINALIZE_WEEK",entityType:"CompetitionWeek",entityId:weekId,classId:user.classId,after:{status:"FINALIZED"}}});});revalidatePath("/");}
