"use server";
import { revalidatePath } from "next/cache";
import { assertWriteAllowed } from "@/lib/license/runtime";
import { z } from "zod";
import { requireTeacher } from "@/lib/auth";
import { db } from "@/lib/db";
import { rangesOverlap, semesterWithinYear, validDateRange } from "@/lib/school-validation";

const text=z.string().trim().min(2).max(100); const date=z.coerce.date();
async function actor(){const u=await requireTeacher();if(!u.schoolId)throw new Error("Tài khoản chưa thuộc trường học.");return u}
export async function saveSchool(formData:FormData){await assertWriteAllowed();const u=await actor();const p=z.object({id:z.string().optional(),name:text,code:z.string().trim().min(2).max(30).regex(/^[A-Za-z0-9-]+$/),status:z.enum(["ACTIVE","INACTIVE"])}).parse(Object.fromEntries(formData));if(u.role!=="SYSTEM_ADMIN"&&p.id!==u.schoolId)throw new Error("Bạn chỉ được sửa trường đang quản lý.");const dup=await db.school.findFirst({where:{code:p.code,NOT:p.id?{id:p.id}:undefined}});if(dup)throw new Error("Mã trường đã tồn tại.");const row=p.id?await db.school.update({where:{id:p.id},data:{name:p.name,code:p.code,status:p.status,archivedAt:p.status==="INACTIVE"?new Date():null}}):await db.school.create({data:{name:p.name,code:p.code,status:p.status}});await db.auditLog.create({data:{userId:u.id,action:p.id?"UPDATE_SCHOOL":"CREATE_SCHOOL",entityType:"School",entityId:row.id,schoolId:row.id,after:p}});revalidatePath("/truong-hoc")}
export async function saveSchoolYear(formData:FormData){await assertWriteAllowed();const u=await actor();const p=z.object({id:z.string().optional(),name:text,startDate:date,endDate:date,isActive:z.coerce.boolean().optional()}).parse(Object.fromEntries(formData));if(!validDateRange(p.startDate,p.endDate))throw new Error("Ngày kết thúc phải sau ngày bắt đầu.");const schoolId=u.schoolId!;await db.$transaction(async tx=>{if(p.isActive)await tx.schoolYear.updateMany({where:{schoolId,isActive:true,NOT:p.id?{id:p.id}:undefined},data:{isActive:false}});const row=p.id?await tx.schoolYear.update({where:{id:p.id,schoolId},data:{name:p.name,startDate:p.startDate,endDate:p.endDate,isActive:!!p.isActive}}):await tx.schoolYear.create({data:{name:p.name,schoolId,startDate:p.startDate,endDate:p.endDate,isActive:!!p.isActive}});await tx.auditLog.create({data:{userId:u.id,action:p.id?"UPDATE_SCHOOL_YEAR":"CREATE_SCHOOL_YEAR",entityType:"SchoolYear",entityId:row.id,schoolId,after:p}})});revalidatePath("/nam-hoc")}
export async function saveSemester(formData:FormData){await assertWriteAllowed();const u=await actor();const p=z.object({id:z.string().optional(),schoolYearId:z.string(),name:text,startDate:date,endDate:date}).parse(Object.fromEntries(formData));const year=await db.schoolYear.findFirst({where:{id:p.schoolYearId,schoolId:u.schoolId!,archivedAt:null}});if(!year||!year.endDate||!semesterWithinYear(p.startDate,p.endDate,year.startDate,year.endDate))throw new Error("Thời gian học kỳ phải nằm trong năm học.");const others=await db.semester.findMany({where:{schoolYearId:year.id,archivedAt:null,NOT:p.id?{id:p.id}:undefined}});if(others.some(s=>rangesOverlap(p.startDate,p.endDate,s.startDate,s.endDate)))throw new Error("Thời gian học kỳ bị chồng lấn.");const row=p.id?await db.semester.update({where:{id:p.id},data:{name:p.name,startDate:p.startDate,endDate:p.endDate}}):await db.semester.create({data:p});await db.auditLog.create({data:{userId:u.id,action:p.id?"UPDATE_SEMESTER":"CREATE_SEMESTER",entityType:"Semester",entityId:row.id,schoolId:u.schoolId,after:p}});revalidatePath("/hoc-ky")}
export async function saveClassroom(formData:FormData){await assertWriteAllowed();const u=await actor();const p=z.object({id:z.string().optional(),name:text,grade:z.string().trim().min(1).max(10),semesterId:z.string(),teacherName:text,status:z.enum(["ACTIVE","INACTIVE"])}).parse(Object.fromEntries(formData));const semester=await db.semester.findFirst({where:{id:p.semesterId,schoolYear:{schoolId:u.schoolId!}}});if(!semester)throw new Error("Học kỳ không thuộc trường đang quản lý.");if(p.id&&!await db.classroom.findFirst({where:{id:p.id,schoolId:u.schoolId!}}))throw new Error("Không có quyền sửa lớp này.");const row=p.id?await db.classroom.update({where:{id:p.id},data:{name:p.name,grade:p.grade,semesterId:p.semesterId,teacherName:p.teacherName,status:p.status,archivedAt:p.status==="INACTIVE"?new Date():null}}):await db.classroom.create({data:{name:p.name,grade:p.grade,schoolId:u.schoolId!,semesterId:p.semesterId,teacherName:p.teacherName,status:p.status}});await db.classMembership.upsert({where:{userId_classId_role:{userId:u.id,classId:row.id,role:"TEACHER"}},update:{active:true,endDate:null},create:{userId:u.id,classId:row.id,role:"TEACHER"}});await db.auditLog.create({data:{userId:u.id,action:p.id?"UPDATE_CLASS":"CREATE_CLASS",entityType:"Classroom",entityId:row.id,schoolId:u.schoolId,classId:row.id,after:p}});revalidatePath("/lop-hoc")}
export async function saveTeam(formData:FormData){await assertWriteAllowed();const u=await actor();const p=z.object({id:z.string().optional(),name:text,classId:z.string()}).parse(Object.fromEntries(formData));const classroom=await db.classroom.findFirst({where:{id:p.classId,schoolId:u.schoolId!}});if(!classroom)throw new Error("Lớp không thuộc phạm vi quản lý.");if(p.id&&!await db.team.findFirst({where:{id:p.id,classId:p.classId}}))throw new Error("Tổ không thuộc lớp này.");const row=p.id?await db.team.update({where:{id:p.id},data:{name:p.name}}):await db.team.create({data:{name:p.name,classId:p.classId}});await db.auditLog.create({data:{userId:u.id,action:p.id?"UPDATE_TEAM":"CREATE_TEAM",entityType:"Team",entityId:row.id,schoolId:u.schoolId,classId:p.classId,after:p}});revalidatePath("/to-hoc-tap")}
export async function archiveTeam(formData:FormData){await assertWriteAllowed();const u=await actor();const id=z.string().parse(formData.get("id"));const team=await db.team.findFirst({where:{id,classroom:{schoolId:u.schoolId!}},include:{_count:{select:{students:true}}}});if(!team)throw new Error("Không tìm thấy tổ.");if(team._count.students)throw new Error("Hãy chuyển hết học sinh trước khi lưu trữ tổ.");await db.$transaction([db.team.update({where:{id},data:{archivedAt:new Date()}}),db.auditLog.create({data:{userId:u.id,action:"ARCHIVE_TEAM",entityType:"Team",entityId:id,schoolId:u.schoolId,classId:team.classId}})]);revalidatePath("/to-hoc-tap")}