"use server";
import { revalidatePath } from "next/cache";
import { redirect } from "next/navigation";
import { z } from "zod";
import { assertWriteAllowed } from "@/lib/license/runtime";
import { db } from "@/lib/db";
import { requireTeacher } from "@/lib/auth";
const date = z.string().regex(/^\d{4}-\d{2}-\d{2}$/), day = (value: string) => new Date(`${value}T00:00:00.000Z`);
const createSchema = z.object({ classId: z.string().min(1), number: z.coerce.number().int().positive(), startDate: date, endDate: date, ruleSetId: z.string().min(1), initialScore: z.coerce.number().int().min(0).max(1000), returnTo: z.string().optional() });
async function assertClass(user: Awaited<ReturnType<typeof requireTeacher>>, classId: string) { if (user.role === "SYSTEM_ADMIN") return; const membership = await db.classMembership.findFirst({ where: { userId: user.id, classId, active: true } }); if (user.classId !== classId && !membership) throw new Error("Bạn không có quyền quản lý lớp này."); }
export async function createCompetitionWeek(_: unknown, formData: FormData) { await assertWriteAllowed(); const user = await requireTeacher(), parsed = createSchema.safeParse(Object.fromEntries(formData)); if (!parsed.success) return { error: "Vui lòng kiểm tra số tuần, ngày và nội quy." }; const data = parsed.data, start = day(data.startDate), end = day(data.endDate); if (end < start) return { error: "Ngày kết thúc không được trước ngày bắt đầu." }; try { await assertClass(user, data.classId); const rule = await db.ruleSet.findFirst({ where: { id: data.ruleSetId, classId: data.classId, status: "PUBLISHED", startDate: { lte: start }, OR: [{ endDate: null }, { endDate: { gte: start } }] } }); if (!rule) return { error: "Nội quy phải thuộc đúng lớp, đã công bố và còn hiệu lực." }; const overlap = await db.competitionWeek.findFirst({ where: { classId: data.classId, startDate: { lte: end }, endDate: { gte: start } } }); if (overlap) return { error: `Khoảng ngày chồng lấn với tuần ${overlap.number}.` }; const created = await db.$transaction(async tx => { const week = await tx.competitionWeek.create({ data: { classId: data.classId, number: data.number, startDate: start, endDate: end, ruleSetId: data.ruleSetId, initialScore: data.initialScore, status: "OPEN" } }); await tx.auditLog.create({ data: { userId: user.id, action: "CREATE_COMPETITION_WEEK", entityType: "CompetitionWeek", entityId: week.id, schoolId: user.schoolId, classId: data.classId, after: { number: data.number, startDate: data.startDate, endDate: data.endDate } } }); return week; }); revalidatePath("/tuan-thi-dua"); if (data.returnTo?.startsWith("/diem-danh?")) redirect(data.returnTo); return { ok: true, message: `Đã tạo tuần ${created.number}.` }; } catch (error) { if (error instanceof Error && error.message.includes("Unique constraint")) return { error: "Số tuần và phiên bản đã tồn tại." }; return { error: error instanceof Error ? error.message : "Không thể tạo tuần." }; } }
export async function createNextWeek(formData: FormData) { await assertWriteAllowed(); const user = await requireTeacher(), classId = z.string().parse(formData.get("classId")); await assertClass(user, classId); const latest = await db.competitionWeek.findFirst({ where: { classId }, orderBy: [{ endDate: "desc" }, { number: "desc" }] }); if (!latest) throw new Error("Hãy tạo tuần đầu tiên trước."); const start = new Date(latest.endDate); start.setUTCDate(start.getUTCDate() + 1); const end = new Date(start); end.setUTCDate(end.getUTCDate() + 6); await db.$transaction([db.competitionWeek.create({ data: { classId, number: latest.number + 1, startDate: start, endDate: end, ruleSetId: latest.ruleSetId, initialScore: latest.initialScore } }), db.auditLog.create({ data: { userId: user.id, action: "CREATE_NEXT_COMPETITION_WEEK", entityType: "CompetitionWeek", classId, schoolId: user.schoolId, after: { number: latest.number + 1 } } })]); revalidatePath("/tuan-thi-dua"); }
export async function deleteEmptyWeek(formData: FormData) { await assertWriteAllowed(); const user = await requireTeacher(), id = z.string().parse(formData.get("id")); const week = await db.competitionWeek.findUnique({ where: { id }, include: { _count: { select: { sessions: true, events: true, results: true, adjustments: true } } } }); if (!week) throw new Error("Không tìm thấy tuần."); await assertClass(user, week.classId); if (week.status !== "OPEN" || Object.values(week._count).some(Boolean)) throw new Error("Chỉ được xóa tuần đang mở chưa có dữ liệu."); await db.$transaction([db.competitionWeek.delete({ where: { id } }), db.auditLog.create({ data: { userId: user.id, action: "DELETE_EMPTY_COMPETITION_WEEK", entityType: "CompetitionWeek", entityId: id, classId: week.classId, schoolId: user.schoolId, before: { number: week.number } } })]); revalidatePath("/tuan-thi-dua"); }
export async function reopenWeek(formData: FormData) { await assertWriteAllowed(); const user = await requireTeacher(), id = z.string().parse(formData.get("id")), reason = z.string().min(5).parse(formData.get("reason")); const week = await db.competitionWeek.findUnique({ where: { id }, include: { results: true, events: true, sessions: { include: { records: true } } } }); if (!week || week.status !== "FINALIZED") throw new Error("Chỉ mở lại tuần đã chốt."); await assertClass(user, week.classId); await db.$transaction(async tx => { await tx.competitionWeekSnapshot.create({ data: { weekId: id, version: week.version, reason, createdBy: user.id, data: JSON.parse(JSON.stringify({ results: week.results, events: week.events, sessions: week.sessions })) } }); await tx.competitionWeek.update({ where: { id }, data: { status: "REOPENED", version: { increment: 1 }, reopenedAt: new Date(), reopenedBy: user.id, reopenReason: reason, finalizedAt: null, finalizedBy: null } }); await tx.auditLog.create({ data: { userId: user.id, action: "REOPEN_COMPETITION_WEEK", entityType: "CompetitionWeek", entityId: id, classId: week.classId, schoolId: user.schoolId, before: { status: "FINALIZED", version: week.version }, after: { status: "REOPENED", version: week.version + 1, reason } } }); }); revalidatePath("/tuan-thi-dua"); }